/* Approximate seed nutrients per 100 g (USDA/BLS-like, rounded).
 * Not lab-accurate — user corrects in the preview sheet before saving.
 * Source label: approximate seed for offline Rohprodukte / fresh produce. */
window.MAHLZEITEN_GRUNDPRODUKTE = [
  /* —— Gemüse —— */
  { id: "gp-paprika-rot", name: "Paprika rot", aliases: ["paprika", "rote paprika", "bell pepper", "red bell pepper", "peperoni", "gemüsepaprika"], category: "gemuese",
    per100: { kcal: 31, protein: 1.0, carbs: 6.0, fat: 0.3, salt: 0.01, sugar: 4.2, fiber: 2.1, satFat: 0.1 } },
  { id: "gp-paprika-gelb", name: "Paprika gelb", aliases: ["gelbe paprika", "yellow bell pepper"], category: "gemuese",
    per100: { kcal: 27, protein: 1.0, carbs: 6.3, fat: 0.2, salt: 0.01, sugar: 4.0, fiber: 0.9, satFat: 0 } },
  { id: "gp-paprika-gruen", name: "Paprika grün", aliases: ["grüne paprika", "green bell pepper"], category: "gemuese",
    per100: { kcal: 20, protein: 0.9, carbs: 4.6, fat: 0.2, salt: 0.01, sugar: 2.4, fiber: 1.7, satFat: 0 } },
  { id: "gp-spitzpaprika", name: "Spitzpaprika", aliases: ["spitz paprika", "pointed pepper", "sweet pointed pepper", "kapia"], category: "gemuese",
    per100: { kcal: 35, protein: 1.2, carbs: 6.5, fat: 0.3, salt: 0.01, sugar: 4.5, fiber: 2.0, satFat: 0.1 } },
  { id: "gp-kohlrabi", name: "Kohlrabi", aliases: ["german turnip", "turnip cabbage", "kohl rabi"], category: "gemuese",
    per100: { kcal: 27, protein: 1.7, carbs: 6.2, fat: 0.1, salt: 0.02, sugar: 2.6, fiber: 3.6, satFat: 0 } },
  { id: "gp-tomate", name: "Tomate", aliases: ["tomaten", "tomato", "rispentomate"], category: "gemuese",
    per100: { kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, salt: 0.01, sugar: 2.6, fiber: 1.2, satFat: 0 } },
  { id: "gp-gurke", name: "Gurke", aliases: ["salatgurke", "cucumber"], category: "gemuese",
    per100: { kcal: 12, protein: 0.6, carbs: 2.2, fat: 0.1, salt: 0.01, sugar: 1.7, fiber: 0.5, satFat: 0 } },
  { id: "gp-zucchini", name: "Zucchini", aliases: ["courgette"], category: "gemuese",
    per100: { kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3, salt: 0.01, sugar: 2.5, fiber: 1.0, satFat: 0.1 } },
  { id: "gp-karotte", name: "Karotte", aliases: ["möhre", "mohrrübe", "carrot", "möhren"], category: "gemuese",
    per100: { kcal: 41, protein: 0.9, carbs: 9.6, fat: 0.2, salt: 0.07, sugar: 4.7, fiber: 2.8, satFat: 0 } },
  { id: "gp-brokkoli", name: "Brokkoli", aliases: ["broccoli"], category: "gemuese",
    per100: { kcal: 34, protein: 2.8, carbs: 7.0, fat: 0.4, salt: 0.03, sugar: 1.7, fiber: 2.6, satFat: 0.1 } },
  { id: "gp-blumenkohl", name: "Blumenkohl", aliases: ["cauliflower"], category: "gemuese",
    per100: { kcal: 25, protein: 1.9, carbs: 5.0, fat: 0.3, salt: 0.03, sugar: 1.9, fiber: 2.0, satFat: 0.1 } },
  { id: "gp-spinat", name: "Spinat", aliases: ["spinach", "blattspinat"], category: "gemuese",
    per100: { kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4, salt: 0.08, sugar: 0.4, fiber: 2.2, satFat: 0.1 } },
  { id: "gp-salat", name: "Kopfsalat", aliases: ["salat", "lettuce", "eisbergsalat", "romanasalat"], category: "gemuese",
    per100: { kcal: 15, protein: 1.4, carbs: 2.9, fat: 0.2, salt: 0.03, sugar: 0.8, fiber: 1.3, satFat: 0 } },
  { id: "gp-zwiebel", name: "Zwiebel", aliases: ["zwiebeln", "onion", "speisezwiebel"], category: "gemuese",
    per100: { kcal: 40, protein: 1.1, carbs: 9.3, fat: 0.1, salt: 0.01, sugar: 4.2, fiber: 1.7, satFat: 0 } },
  { id: "gp-knoblauch", name: "Knoblauch", aliases: ["garlic"], category: "gemuese",
    per100: { kcal: 149, protein: 6.4, carbs: 33.1, fat: 0.5, salt: 0.02, sugar: 1.0, fiber: 2.1, satFat: 0.1 } },
  { id: "gp-kartoffel", name: "Kartoffel", aliases: ["kartoffeln", "potato", "erdäpfel"], category: "gemuese",
    per100: { kcal: 77, protein: 2.0, carbs: 17.5, fat: 0.1, salt: 0.01, sugar: 0.8, fiber: 2.1, satFat: 0 } },
  { id: "gp-suesskartoffel", name: "Süßkartoffel", aliases: ["suesskartoffel", "sweet potato", "batate"], category: "gemuese",
    per100: { kcal: 86, protein: 1.6, carbs: 20.1, fat: 0.1, salt: 0.05, sugar: 4.2, fiber: 3.0, satFat: 0 } },
  { id: "gp-champignon", name: "Champignon", aliases: ["pilze", "mushroom", "weißpilz"], category: "gemuese",
    per100: { kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3, salt: 0.01, sugar: 2.0, fiber: 1.0, satFat: 0.1 } },
  { id: "gp-aubergine", name: "Aubergine", aliases: ["eggplant", "melanzani"], category: "gemuese",
    per100: { kcal: 25, protein: 1.0, carbs: 5.9, fat: 0.2, salt: 0.01, sugar: 3.5, fiber: 3.0, satFat: 0 } },
  { id: "gp-lauch", name: "Lauch", aliases: ["porree", "leek"], category: "gemuese",
    per100: { kcal: 61, protein: 1.5, carbs: 14.2, fat: 0.3, salt: 0.02, sugar: 3.9, fiber: 1.8, satFat: 0.1 } },
  { id: "gp-sellerie", name: "Staudensellerie", aliases: ["sellerie", "celery", "stangensellerie"], category: "gemuese",
    per100: { kcal: 14, protein: 0.7, carbs: 3.0, fat: 0.2, salt: 0.08, sugar: 1.3, fiber: 1.6, satFat: 0 } },
  { id: "gp-rotkohl", name: "Rotkohl", aliases: ["blaukraut", "red cabbage"], category: "gemuese",
    per100: { kcal: 31, protein: 1.4, carbs: 7.4, fat: 0.2, salt: 0.03, sugar: 3.8, fiber: 2.1, satFat: 0 } },
  { id: "gp-weisskohl", name: "Weißkohl", aliases: ["weisskohl", "kraut", "white cabbage", "cabbage"], category: "gemuese",
    per100: { kcal: 25, protein: 1.3, carbs: 5.8, fat: 0.1, salt: 0.02, sugar: 3.2, fiber: 2.5, satFat: 0 } },
  { id: "gp-rosenkohl", name: "Rosenkohl", aliases: ["brussels sprouts"], category: "gemuese",
    per100: { kcal: 43, protein: 3.4, carbs: 8.9, fat: 0.3, salt: 0.03, sugar: 2.2, fiber: 3.8, satFat: 0.1 } },
  { id: "gp-bohne", name: "Grüne Bohnen", aliases: ["bohnen", "green beans", "schnittbohnen", "prinzessbohnen"], category: "gemuese",
    per100: { kcal: 31, protein: 1.8, carbs: 7.0, fat: 0.2, salt: 0.01, sugar: 3.3, fiber: 2.7, satFat: 0 } },
  { id: "gp-erbse", name: "Erbsen", aliases: ["erbse", "peas", "grüne erbsen"], category: "gemuese",
    per100: { kcal: 81, protein: 5.4, carbs: 14.4, fat: 0.4, salt: 0.01, sugar: 5.7, fiber: 5.1, satFat: 0.1 } },
  { id: "gp-mais", name: "Mais", aliases: ["corn", "zuckermais"], category: "gemuese",
    per100: { kcal: 86, protein: 3.3, carbs: 19.0, fat: 1.2, salt: 0.02, sugar: 6.3, fiber: 2.7, satFat: 0.2 } },
  { id: "gp-rote-beete", name: "Rote Beete", aliases: ["rote bete", "beetroot", "rande"], category: "gemuese",
    per100: { kcal: 43, protein: 1.6, carbs: 9.6, fat: 0.2, salt: 0.08, sugar: 6.8, fiber: 2.8, satFat: 0 } },
  { id: "gp-radieschen", name: "Radieschen", aliases: ["radish", "radieschen"], category: "gemuese",
    per100: { kcal: 16, protein: 0.7, carbs: 3.4, fat: 0.1, salt: 0.04, sugar: 1.9, fiber: 1.6, satFat: 0 } },
  { id: "gp-spargel", name: "Spargel", aliases: ["asparagus", "grüner spargel", "weißer spargel"], category: "gemuese",
    per100: { kcal: 20, protein: 2.2, carbs: 3.9, fat: 0.1, salt: 0.01, sugar: 1.9, fiber: 2.1, satFat: 0 } },
  { id: "gp-avocado", name: "Avocado", aliases: ["avocado"], category: "gemuese",
    per100: { kcal: 160, protein: 2.0, carbs: 8.5, fat: 14.7, salt: 0.02, sugar: 0.7, fiber: 6.7, satFat: 2.1 } },
  { id: "gp-fenchel", name: "Fenchel", aliases: ["fennel"], category: "gemuese",
    per100: { kcal: 31, protein: 1.2, carbs: 7.3, fat: 0.2, salt: 0.05, sugar: 3.9, fiber: 3.1, satFat: 0 } },
  { id: "gp-paprika-mix", name: "Paprika gemischt", aliases: ["paprikamix", "paprika mix", "bunte paprika"], category: "gemuese",
    per100: { kcal: 28, protein: 1.0, carbs: 5.5, fat: 0.3, salt: 0.01, sugar: 3.8, fiber: 1.8, satFat: 0.1 } },

  /* —— Obst —— */
  { id: "gp-apfel", name: "Apfel", aliases: ["äpfel", "apple", "aepfel"], category: "obst",
    per100: { kcal: 52, protein: 0.3, carbs: 13.8, fat: 0.2, salt: 0, sugar: 10.4, fiber: 2.4, satFat: 0 } },
  { id: "gp-banane", name: "Banane", aliases: ["bananen", "banana"], category: "obst",
    per100: { kcal: 89, protein: 1.1, carbs: 22.8, fat: 0.3, salt: 0, sugar: 12.2, fiber: 2.6, satFat: 0.1 } },
  { id: "gp-orange", name: "Orange", aliases: ["orangen", "apfelsine"], category: "obst",
    per100: { kcal: 47, protein: 0.9, carbs: 11.8, fat: 0.1, salt: 0, sugar: 9.4, fiber: 2.4, satFat: 0 } },
  { id: "gp-birne", name: "Birne", aliases: ["birnen", "pear"], category: "obst",
    per100: { kcal: 57, protein: 0.4, carbs: 15.2, fat: 0.1, salt: 0, sugar: 9.8, fiber: 3.1, satFat: 0 } },
  { id: "gp-erdbeere", name: "Erdbeere", aliases: ["erdbeeren", "strawberry", "strawberries"], category: "obst",
    per100: { kcal: 32, protein: 0.7, carbs: 7.7, fat: 0.3, salt: 0, sugar: 4.9, fiber: 2.0, satFat: 0 } },
  { id: "gp-blaubeere", name: "Blaubeere", aliases: ["heidelbeere", "blueberry", "blueberries"], category: "obst",
    per100: { kcal: 57, protein: 0.7, carbs: 14.5, fat: 0.3, salt: 0, sugar: 10.0, fiber: 2.4, satFat: 0 } },
  { id: "gp-himbeere", name: "Himbeere", aliases: ["himbeeren", "raspberry"], category: "obst",
    per100: { kcal: 52, protein: 1.2, carbs: 11.9, fat: 0.7, salt: 0, sugar: 4.4, fiber: 6.5, satFat: 0 } },
  { id: "gp-traube", name: "Weintraube", aliases: ["trauben", "grape", "weinbeeren"], category: "obst",
    per100: { kcal: 69, protein: 0.7, carbs: 18.1, fat: 0.2, salt: 0, sugar: 15.5, fiber: 0.9, satFat: 0 } },
  { id: "gp-kiwi", name: "Kiwi", aliases: ["kiwis"], category: "obst",
    per100: { kcal: 61, protein: 1.1, carbs: 14.7, fat: 0.5, salt: 0, sugar: 9.0, fiber: 3.0, satFat: 0 } },
  { id: "gp-mango", name: "Mango", aliases: ["mangos"], category: "obst",
    per100: { kcal: 60, protein: 0.8, carbs: 15.0, fat: 0.4, salt: 0, sugar: 13.7, fiber: 1.6, satFat: 0.1 } },
  { id: "gp-ananas", name: "Ananas", aliases: ["pineapple"], category: "obst",
    per100: { kcal: 50, protein: 0.5, carbs: 13.1, fat: 0.1, salt: 0, sugar: 9.9, fiber: 1.4, satFat: 0 } },
  { id: "gp-zitrone", name: "Zitrone", aliases: ["zitronen", "lemon"], category: "obst",
    per100: { kcal: 29, protein: 1.1, carbs: 9.3, fat: 0.3, salt: 0, sugar: 2.5, fiber: 2.8, satFat: 0 } },
  { id: "gp-limette", name: "Limette", aliases: ["limetten", "lime"], category: "obst",
    per100: { kcal: 30, protein: 0.7, carbs: 10.5, fat: 0.2, salt: 0, sugar: 1.7, fiber: 2.8, satFat: 0 } },
  { id: "gp-pfirsich", name: "Pfirsich", aliases: ["pfirsiche", "peach"], category: "obst",
    per100: { kcal: 39, protein: 0.9, carbs: 9.5, fat: 0.3, salt: 0, sugar: 8.4, fiber: 1.5, satFat: 0 } },
  { id: "gp-pflaume", name: "Pflaume", aliases: ["pflaumen", "zwetschge", "plum"], category: "obst",
    per100: { kcal: 46, protein: 0.7, carbs: 11.4, fat: 0.3, salt: 0, sugar: 9.9, fiber: 1.4, satFat: 0 } },
  { id: "gp-kirsche", name: "Kirsche", aliases: ["kirschen", "cherry", "süßkirsche"], category: "obst",
    per100: { kcal: 63, protein: 1.1, carbs: 16.0, fat: 0.2, salt: 0, sugar: 12.8, fiber: 2.1, satFat: 0 } },
  { id: "gp-wassermelone", name: "Wassermelone", aliases: ["melone", "watermelon"], category: "obst",
    per100: { kcal: 30, protein: 0.6, carbs: 7.6, fat: 0.2, salt: 0, sugar: 6.2, fiber: 0.4, satFat: 0 } },

  /* —— Fleisch / Fisch / Ei —— */
  { id: "gp-haehnchenbrust", name: "Hähnchenbrust", aliases: ["huhn brust", "chicken breast", "hühnchenbrust", "haehnchen"], category: "fleisch",
    per100: { kcal: 110, protein: 23.1, carbs: 0, fat: 1.2, salt: 0.15, sugar: 0, fiber: 0, satFat: 0.3 } },
  { id: "gp-putenbrust", name: "Putenbrust", aliases: ["truthahn", "turkey breast", "pute"], category: "fleisch",
    per100: { kcal: 104, protein: 24.0, carbs: 0, fat: 0.7, salt: 0.15, sugar: 0, fiber: 0, satFat: 0.2 } },
  { id: "gp-rinderhack", name: "Rinderhackfleisch (5% Fett)", aliases: ["hackfleisch rind", "ground beef", "hack rind"], category: "fleisch",
    per100: { kcal: 137, protein: 21.0, carbs: 0, fat: 5.0, salt: 0.18, sugar: 0, fiber: 0, satFat: 2.0 } },
  { id: "gp-schweinefilet", name: "Schweinefilet", aliases: ["schwein filet", "pork tenderloin"], category: "fleisch",
    per100: { kcal: 120, protein: 21.0, carbs: 0, fat: 3.5, salt: 0.15, sugar: 0, fiber: 0, satFat: 1.2 } },
  { id: "gp-lachs", name: "Lachs (roh)", aliases: ["salmon", "lachsfilet"], category: "fleisch",
    per100: { kcal: 208, protein: 20.4, carbs: 0, fat: 13.4, salt: 0.15, sugar: 0, fiber: 0, satFat: 3.1 } },
  { id: "gp-thunfisch", name: "Thunfisch (roh)", aliases: ["tuna", "thunfischfilet"], category: "fleisch",
    per100: { kcal: 144, protein: 23.3, carbs: 0, fat: 4.9, salt: 0.12, sugar: 0, fiber: 0, satFat: 1.3 } },
  { id: "gp-ei", name: "Hühnerei (ganz)", aliases: ["ei", "eier", "egg", "hühnerei"], category: "fleisch",
    per100: { kcal: 143, protein: 12.6, carbs: 0.7, fat: 9.9, salt: 0.35, sugar: 0.4, fiber: 0, satFat: 3.1 } },
  { id: "gp-eiklar", name: "Eiweiß (Eiklar)", aliases: ["eiweiss", "egg white", "klar"], category: "fleisch",
    per100: { kcal: 52, protein: 11.0, carbs: 0.7, fat: 0.2, salt: 0.4, sugar: 0.7, fiber: 0, satFat: 0 } },

  /* —— Milchprodukte (Roh/Basis) —— */
  { id: "gp-milch-15", name: "Milch 1,5 %", aliases: ["milch", "fettarme milch", "low fat milk"], category: "milch",
    per100: { kcal: 47, protein: 3.4, carbs: 4.9, fat: 1.5, salt: 0.13, sugar: 4.9, fiber: 0, satFat: 1.0 } },
  { id: "gp-joghurt", name: "Joghurt natur 1,5 %", aliases: ["joghurt", "yoghurt", "yogurt natur"], category: "milch",
    per100: { kcal: 49, protein: 4.0, carbs: 5.0, fat: 1.5, salt: 0.13, sugar: 5.0, fiber: 0, satFat: 1.0 } },
  { id: "gp-quark", name: "Magerquark 0,2 %", aliases: ["quark", "magerquark", "speisequark"], category: "milch",
    per100: { kcal: 67, protein: 12.0, carbs: 4.0, fat: 0.2, salt: 0.1, sugar: 4.0, fiber: 0, satFat: 0.1 } },
  { id: "gp-skyr", name: "Skyr natur", aliases: ["skyr"], category: "milch",
    per100: { kcal: 63, protein: 11.0, carbs: 4.0, fat: 0.2, salt: 0.1, sugar: 4.0, fiber: 0, satFat: 0.1 } },
  { id: "gp-butter", name: "Butter", aliases: ["butter"], category: "milch",
    per100: { kcal: 717, protein: 0.9, carbs: 0.1, fat: 81.1, salt: 0.02, sugar: 0.1, fiber: 0, satFat: 51.4 } },

  /* —— Grundnahrung / Öle —— */
  { id: "gp-reis", name: "Reis (roh)", aliases: ["reis", "rice", "basmati", "langkornreis"], category: "grund",
    per100: { kcal: 349, protein: 7.0, carbs: 78.0, fat: 0.6, salt: 0.01, sugar: 0.1, fiber: 1.3, satFat: 0.2 } },
  { id: "gp-nudeln", name: "Nudeln (roh)", aliases: ["nudel", "pasta", "spaghetti"], category: "grund",
    per100: { kcal: 359, protein: 12.5, carbs: 71.0, fat: 1.5, salt: 0.01, sugar: 3.0, fiber: 3.2, satFat: 0.3 } },
  { id: "gp-haferflocken", name: "Haferflocken", aliases: ["hafer", "oats", "oatmeal"], category: "grund",
    per100: { kcal: 370, protein: 13.5, carbs: 58.7, fat: 7.0, salt: 0.01, sugar: 0.7, fiber: 10.0, satFat: 1.3 } },
  { id: "gp-vollkornbrot", name: "Vollkornbrot", aliases: ["brot", "vollkorn", "whole wheat bread"], category: "grund",
    per100: { kcal: 250, protein: 8.5, carbs: 41.0, fat: 3.5, salt: 1.2, sugar: 3.0, fiber: 7.5, satFat: 0.6 } },
  { id: "gp-olivenoel", name: "Olivenöl", aliases: ["olivenoel", "olive oil", "öl"], category: "grund",
    per100: { kcal: 884, protein: 0, carbs: 0, fat: 100, salt: 0, sugar: 0, fiber: 0, satFat: 13.8 } },

  /* —— Gewürze —— */
  { id: "gp-salz", name: "Speisesalz", aliases: ["salz", "salt", "kochsalz"], category: "gewuerz",
    per100: { kcal: 0, protein: 0, carbs: 0, fat: 0, salt: 100, sugar: 0, fiber: 0, satFat: 0 } },
  { id: "gp-pfeffer", name: "Schwarzer Pfeffer", aliases: ["pfeffer", "black pepper"], category: "gewuerz",
    per100: { kcal: 251, protein: 10.4, carbs: 63.9, fat: 3.3, salt: 0.05, sugar: 0.6, fiber: 25.3, satFat: 1.0 } },
  { id: "gp-paprikapulver", name: "Paprikapulver (süß)", aliases: ["paprika pulver", "paprika powder", "edelsüß"], category: "gewuerz",
    per100: { kcal: 282, protein: 14.1, carbs: 53.9, fat: 12.9, salt: 0.09, sugar: 10.3, fiber: 34.9, satFat: 2.1 } },
  { id: "gp-oregano", name: "Oregano (getrocknet)", aliases: ["oregano"], category: "gewuerz",
    per100: { kcal: 265, protein: 9.0, carbs: 68.9, fat: 4.3, salt: 0.06, sugar: 4.1, fiber: 42.5, satFat: 1.6 } },
  { id: "gp-basilikum", name: "Basilikum (frisch)", aliases: ["basilikum", "basil"], category: "gewuerz",
    per100: { kcal: 23, protein: 3.2, carbs: 2.7, fat: 0.6, salt: 0.01, sugar: 0.3, fiber: 1.6, satFat: 0 } },
  { id: "gp-kurkuma", name: "Kurkuma", aliases: ["curcuma", "turmeric", "gelbuurzel"], category: "gewuerz",
    per100: { kcal: 312, protein: 9.7, carbs: 67.1, fat: 3.3, salt: 0.07, sugar: 3.2, fiber: 22.7, satFat: 1.8 } },
  { id: "gp-zimt", name: "Zimt", aliases: ["cinnamon"], category: "gewuerz",
    per100: { kcal: 247, protein: 4.0, carbs: 80.6, fat: 1.2, salt: 0.03, sugar: 2.2, fiber: 53.1, satFat: 0.3 } },
  { id: "gp-chili", name: "Chilipulver", aliases: ["chili", "cayenne", "chilli"], category: "gewuerz",
    per100: { kcal: 282, protein: 13.5, carbs: 49.7, fat: 14.3, salt: 0.08, sugar: 7.2, fiber: 34.8, satFat: 2.5 } },
  { id: "gp-zucker", name: "Haushaltszucker", aliases: ["zucker", "sugar", "raffinade"], category: "gewuerz",
    per100: { kcal: 400, protein: 0, carbs: 100, fat: 0, salt: 0, sugar: 100, fiber: 0, satFat: 0 } },
];
